language: node_js
before_install:
  - nvm install 8
  - nvm use node
  - npm -v
  - node -v
install:
  - npm ci
cache:
  directories:
  - "$HOME/.npm"
before_script:
  - node ./app.js &
  - sleep 5
  - node ./app-peer.js &
  - sleep 5
script:
  - npm test
